# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatoEnfermo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('objetivo', models.FloatField()),
                ('recaudado', models.FloatField(default=0)),
                ('fecha', models.DateField()),
                ('prioridad', models.IntegerField(choices=[(0, 'Baja'), (1, 'Media'), (2, 'Alta'), (3, 'Urgente')])),
                ('imagen_principal', models.ImageField(max_length=255, upload_to='photo/%y%m%d')),
                ('imagen1', models.ImageField(max_length=255, upload_to='photo/%y%m%d')),
                ('imagen2', models.ImageField(max_length=255, upload_to='photo/%y%m%d')),
                ('imagen3', models.ImageField(max_length=255, upload_to='photo/%y%m%d')),
                ('imagen4', models.ImageField(max_length=255, upload_to='photo/%y%m%d')),
            ],
        ),
    ]
