# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='direccion',
            field=models.CharField(default=213, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='pagina_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='pagina_google',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='pagina_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='pagina_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='telefono',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="El telefono debe tener este formato: '+999999999'. Hasta 15 digitos permitidos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
