# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170226_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='paypal_url',
            field=models.URLField(default=213),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='pagina_facebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='pagina_google',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='pagina_linkedin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='pagina_twitter',
            field=models.URLField(),
        ),
    ]
