# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170226_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='imagen_principal',
            field=models.ImageField(default='asd', max_length=255, upload_to='config'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='descripcionPersona1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='descripcionPersona2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='imagenPersona1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='config'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='imagenPersona2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='config'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='pagina_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='pagina_google',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='pagina_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='pagina_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='paypal_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='telefono',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="El telefono debe tener este formato: '+999999999'. Hasta 15 digitos permitidos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='imagen1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photo/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='imagen2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photo/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='imagen3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photo/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='imagen4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photo/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='objetivo',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='prioridad',
            field=models.IntegerField(blank=True, choices=[(0, 'Baja'), (1, 'Media'), (2, 'Alta'), (3, 'Urgente')]),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='recaudado',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
