# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170320_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatoenfermo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='objetivo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='prioridad',
            field=models.IntegerField(blank=True, choices=[(0, 'Baja'), (1, 'Media'), (2, 'Alta'), (3, 'Urgente')], null=True),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='recaudado',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
