# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170321_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatoenfermo',
            name='imagen4',
        ),
        migrations.AddField(
            model_name='gatoenfermo',
            name='en_adopcion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatoenfermo',
            name='recaudar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
