# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 15:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170321_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name_plural': 'Configuracion'},
        ),
        migrations.AlterModelOptions(
            name='gatoenfermo',
            options={'verbose_name_plural': 'Gatos Enfermos'},
        ),
        migrations.AddField(
            model_name='gatoenfermo',
            name='imagen4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photo/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='gatoenfermo',
            name='prioridad',
            field=models.IntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Urgente')], null=True),
        ),
    ]
