# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 15:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170324_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='quienes_somos',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
