# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 15:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170324_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatoFinalFeliz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('imagen_principal', models.ImageField(max_length=255, upload_to='photo/%y%m%d')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('imagen1', models.ImageField(blank=True, max_length=255, null=True, upload_to='photo/%y%m%d')),
                ('imagen2', models.ImageField(blank=True, max_length=255, null=True, upload_to='photo/%y%m%d')),
                ('imagen3', models.ImageField(blank=True, max_length=255, null=True, upload_to='photo/%y%m%d')),
                ('imagen4', models.ImageField(blank=True, max_length=255, null=True, upload_to='photo/%y%m%d')),
            ],
            options={
                'verbose_name_plural': 'Gatos Finales Felices',
            },
        ),
        migrations.AddField(
            model_name='configuracion',
            name='protocolo_parrafo_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='protocolo_parrafo_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
