# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 18:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170402_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='protocolo_parrafo_2',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='teaming_parrafo_1',
            field=ckeditor.fields.RichTextField(default='asd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='protocolo_parrafo_1',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
