# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170402_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='teaming_link',
            field=models.URLField(default='http://teaming.net/asociacioncero'),
        ),
    ]
