# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 20:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_configuracion_ayudanos_parrafo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='ayudanos_footer',
            field=ckeditor.fields.RichTextField(default='asd'),
            preserve_default=False,
        ),
    ]
